version: '3.8'

services:
  reolink-processor:
    build: .
    environment:
      - REOLINK_HOST=${REOLINK_HOST:-192.168.10.50}
      - REOLINK_USER=${REOLINK_USER:-admin}
      - REOLINK_PASS=${REOLINK_PASS}
      - REOLINK_PORT=${REOLINK_PORT:-80}
      - REOLINK_CHANNEL=${REOLINK_CHANNEL:-0}
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
    network_mode: host
    restart: unless-stopped